### ISSUE TITLE
Request to show the generated url when 'Can't find field for image' 

### ISSUE THREAD

**Issue by majerus1223** [Dalvany/dalvany-image-panel#11]
I have been struggling to get an image to show in the image panel.  If the image panel would show the 'generated' url it created that might be helpful for troubleshooting panel issues.

Thanks!

**Comment by Dalvany** [comment]
Hello, this message appear when the panel can't find the selected field that should be used to construct the url, so it can't even generate the url. This error message should contains the field name, if you remember when it happens, can you confirm that if it was the case ?   
To see the generated url, you can inspect HTML element with your browser's developper tools (at least if you use firefox or chrome, I don't know for other such as opera or edge).  
Anyway, I can :
* add more log in JS console
* add a checkbox in the panel configuration to enable url display in tooltip (but you won't be able to copy/paste) for debugging purpose

**Comment by majerus1223** [comment]
Good call on developer tools, I was able to get this to work yesterday but had some major issues extracting prometheus labels, within grafana. (grafana issue not this at all) 

If you could add logging that would be awesome.. thanks for the great plugin !

**Comment by Dalvany** [comment]
Thank you !  
I will add some logging especially in case of errors.

**Comment by Dalvany** [comment]
Doesn't seems that I can do debug and info logging, there's a linter rule to prevent it.

**Comment by Dalvany** [comment]
Perhaps using [grafana's alerts](https://developers.grafana.com/ui/latest/index.html?path=/story/overlays-alert--examples) if possible.
