### ISSUE TITLE
FR: Use Grafana variables in settings

### ISSUE THREAD

**Issue by corgan2222** [Dalvany/dalvany-image-panel#14]
It would be great if we could use variables which are defined in the dashboard settings in the plugins settings.
In a dashboard which uses your plugin a lot, and we want to share, it would be much more easy for the user to add the url once in the settings.

This would be great on
- Base URL
- width
- height

Example of heavy use of your plugin: https://forums.unraid.net/topic/96895-ultimate-unraid-dashboard-uud/

**Comment by Dalvany** [comment]
Hello, thanks for using the plugin.
I don't know how to do it but I'll try.

**Comment by corgan2222** [comment]
As I also never have developed a grafana plugin, I have no idea. 
But maybe 
https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/
is a good starting point.

Thanks a lot and good luck. :)

**Comment by Dalvany** [comment]
Thanks for all the links ! I'll look into that !

**Comment by Dalvany** [comment]
It seems simple

**Comment by Dalvany** [comment]
I shouldn't have close the issue. I've done it and I try to build release candidate so you can test it and see if it's ok.

**Comment by Dalvany** [comment]
@corgan2222, I made a [prerelease](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.3.0) tell me if it's ok.  
I already make a PR to made it available through grafana.com because I'm a little bit confuse by the signing plugin workflow.

**Comment by corgan2222** [comment]
Hey, sorry I crashed my home lab and can't test ATM. Hope to get everything back2work on the weekend.

**Comment by Dalvany** [comment]
Hello, sorry to hear that, I hope you didn't loose anything.

**Comment by corgan2222** [comment]
no no, nothing lost :)

I tested the new function and it runs great! Thanks a lot!
https://i.imgur.com/FYIhZYy.png

**Comment by Dalvany** [comment]
Great, I'll close this ticket then.
