### ISSUE TITLE
[FR] Overlays and Underline

### ISSUE THREAD

**Issue by corgan2222** [Dalvany/dalvany-image-panel#19]
Hello again,

i hope it's ok, to have some new feature request. :)
As I wrote in my last FR we are using your plugin for monitoring docker/vm status.

**Overlays**

To only have to use one table/panel for displaying running/stopped VMs, it would be great to have a visual hint on the vms status. Maybe show a red overlay on errors, or make it black/whit if stopped. So it would be much easier to see what's going on, if there is a lot of containers/vms.

The settings could look like this:

- Color Code -> Choose Field with text/status

Or even cooler, to use the image as Background and use a metric field like cpu usage as colored bargraph overlay.

ATM we're using an API which returns something like this

VMs
  foo_Server
    stopped
  bar_server
    running
    
    
**Underline**

Quick on here. It would be great to have the option to display a Field as Underline. Sometimes there are several dockers with the same icon, like grafana-loki and graphana-promtail.

**Comment by Dalvany** [comment]
Hello,
For the overlay I'm not sure what's the best way doing it :
* black/white : it allows only two possible values. It works for your use case but it's too specific.
* a color seems better, I think about a small square on the corner of the image, but I need to find a way to be sure that it will be visible whatever the color below is (for example, with your [`Zabbix` icon](https://i.imgur.com/FYIhZYy.png), using red overlay might not be visible.

For underline, though it's not directly visible can't the tooltip help in that case ? I'll try something anyway but I think that if the text is too long, it won't look terrible.

Note to myself : maybe this CSS could help with underline
```css
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
```

**Comment by corgan2222** [comment]
Yes you are right, color make more sense to be more flexible. 
And Icon would also be nice, if this could be chosen from an url/local source.

You may take a look at the "button panel". The dev had implemented some nice styling features. Maybe this can save some time.
https://grafana.com/grafana/plugins/cloudspout-button-panel/

**Comment by Dalvany** [comment]
Hello @corgan2222 , I've finish the overlay, can you test this [pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.3.0) (better on a new dashboard in case it has some issues) ?
Here's [how it looks](https://raw.githubusercontent.com/Dalvany/dalvany-image-panel/master/src/img/screenshot04.png).
There's [documentation](https://github.com/Dalvany/dalvany-image-panel#overlay-options) on how to configure it. Let me know if there's some way to improve the readme.
Note that there isn't the `underline` options. Can you open a separate issue for this ? But don't except it soon though.

**Comment by corgan2222** [comment]
hey, im atm out of office, but will give this a try asap! Thanks a lot for you work!
greetz

**Comment by Dalvany** [comment]
Good thing you couldn't test right know I had to make a small fix

**Comment by Dalvany** [comment]
Hello, I don't know if you had time to test yet but I made a change in configuration option and remove the switch to enable/disable overlay.

**Comment by Dalvany** [comment]
I finally made the underline too. Let me know if it's ok.

**Comment by corgan2222** [comment]
hey.. i tryed 2.3.0 but i could not find the new overlay options?

![grafik](https://user-images.githubusercontent.com/12233951/117992075-eb2ef700-b33e-11eb-9bff-73611ce40eda.png)

**Comment by Dalvany** [comment]
I just tested the pre-release zip with a fresh grafana 7.5.5 install. It seems to work
![image](https://user-images.githubusercontent.com/9901407/118039079-36153280-b370-11eb-95bd-4f81cf7cfbcb.png)

Can you check plugin version directly inside grafana ?
![image](https://user-images.githubusercontent.com/9901407/118039179-56dd8800-b370-11eb-8e05-42f35efeeecc.png)

What version of grafana are you using ?

**Comment by corgan2222** [comment]
im using the latest[ unraid docker ](https://forums.unraid.net/topic/49775-support-for-atribes-repo-docker-images/)container Grafana v7.4.3 (010f20c1c8)

and installed with 

`grafana-cli --pluginUrl https://github.com/Dalvany/dalvany-image-panel/releases/download/v2.3.0/dalvany-imag
e-panel-2.3.0.zip plugins install dalvany-image-panel`

**Comment by Dalvany** [comment]
Have you restart grafana after installing plugin ?  
How do you run you're container ? If you're image is from official grafana image, you should use `GF_INSTALL_PLUGINS=http://plugin-domain.com/my-custom-plugin.zip;custom-plugin` 
I just tried this docker run, and it worked :
```shell
docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=https://github.com/Dalvany/dalvany-image-panel/releases/download/v2.3.0/dalvany-image-panel-2.3.0.zip;dalvany-image-panel" grafana/grafana:7.4.3
```
Can you check from inside your grafana instance that it is the right plugin version that is loaded ?

**Comment by Dalvany** [comment]
Or perhaps it's the cache browser

**Comment by Dalvany** [comment]
Hello @corgan2222 I've been able to test more and reproduce. I think it's because the plugin is already installed and that when I started using grafana's github workflow there was a change in directory layout of the zip.
Can you either try :
* running a new container installing `https://github.com/Dalvany/dalvany-image-panel/releases/download/v2.3.0/dalvany-imag e-panel-2.3.0.zip` using `GF_INSTALL_PLUGINS` env variable.
* or using [this zip](https://github.com/Dalvany/dalvany-image-panel/releases/download/v2.3.0/dalvany-image-panel-with-dist-2.3.0.zip) in your current running container (it is with the `dist` directory).

**Comment by corgan2222** [comment]
ha.. i just deleted and reinstalled it!
Now it works perfect!!

![grafik](https://user-images.githubusercontent.com/12233951/118616318-e1374900-b7c1-11eb-873d-13925a99ec9f.png)

awesome  job!!!!

**Comment by Dalvany** [comment]
Great, then I'll make the pull request to publish this version on grafana.

**Comment by corgan2222** [comment]
great! thanks again!
