### ISSUE TITLE
Image panel does not fill up the whole width of panel

### ISSUE THREAD

**Issue by jyuteo** [Dalvany/dalvany-image-panel#31]
Hi, when displaying the images, even though I have adjusted the panel width to fit the window, the images are only shown in the middle of the whole panel, I am hoping that there is no empty space on both sides so that more images can be displayed in one row.

As compared to the table panel above, the content of the table can span the whole width of the table panel.

May I know how to style the CSS to achieve that? Thanks.

![image](https://user-images.githubusercontent.com/66994322/121874882-60288e80-cd3a-11eb-8e72-3d14a6d2cec8.png)

**Comment by Dalvany** [comment]
Hello @jyuteo I have the same bug, didn't notice it because never had to use full dashboard width. I'm trying to find how to solve it.

**Comment by Dalvany** [comment]
It seems that my `.container` css class collide with one of grafana. I'll fix that in the next version.
In my `.container` css class you need to put :
```css
max-width: unset;
```
Beware that if you're using version 2.2.1 of the plugin, files are signed, grafana might not load the plugin, you'll probably need to delete the manifest file and if you're using grafana 8 you'll have to allow loading unsigned plugin.

See in the folloing capture that unseting max-width from browser dev tool seems to fix the issue
![image](https://user-images.githubusercontent.com/9901407/121929699-c369ef00-cd41-11eb-9ecb-a4ca8287311c.png)

**Comment by Dalvany** [comment]
I published [this pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.3.0) that fix the issue. Please note that it's unsigned as I'm not able to do that right now.

**Comment by jyuteo** [comment]
It works well now, thanks!

**Comment by Dalvany** [comment]
Great ! Thank you for the test of the fix !
