### ISSUE TITLE
Url tag is embedded into image optionally

### ISSUE THREAD

**Issue by ivanshilo** [Dalvany/dalvany-image-panel#33]
It would be usefull to be able to click onto the image and open the image url in the new tab, for example to see the image in a full size.

**Comment by Dalvany** [comment]
Hello @ivanshilo, thank you for using this plugin and reporting this request.
Can you tell me what version of the plugin you're using and can you tell if the contextual menu works ? I think if it's 2.2.0 or 2.2.1 #15 bug might prevent you from right clicking on the image to open the enu (I never tried with that version). It will be fixed in the next version, I just tested with [this pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.3.0) that you can open the image in new tab from contextual menu.

**Comment by ivanshilo** [comment]
It is working indeed in 2.3.0. Thanks! For mobile devices right click is not available, thats why I said that click on the image itself would be opening it in a new tab (optionaly). But for non-mobile platforms right-click is more than enough of course. Thanks for a great plugin!

**Comment by Dalvany** [comment]
Hello, I don't know what mobile os and what browser your using, but with firefox on Android, a "long click" on the image brings up a context menu, allowing to open image in new tab. I think it won't work with version 2.2.0 and 2.2.1 though, because of #15 bug but should be fine with next version.

**Comment by ivanshilo** [comment]
Long click is not exactly what we wanted to have. We have changed your code a bit wrapping img tag with a' href' tag using the same url and got required behavior.

**Comment by Dalvany** [comment]
Ok, I'm not sure I understand what's wrong with mobile. I'll probably do something later anyway, could be useful to open an arbitrary URL.

**Comment by Dalvany** [comment]
I'll publish the release on grafana.

**Comment by ivanshilo** [comment]
Release 2.4.0 was tested and it is working good. Feature of automatic image opening working good. I like less that I have to enter URL parameters twice. I understand the idea that maybe by clicking on the image, another image in bigger resolution can be requested but by default it is not the case. It could be solved by adding another toggle control that uses "default" URL settings or allows to override.
Another moment - optional text under images is left aligned. It should be central aligned to my taste. I cannot fix it by adding whitespaces in the field value, your code removes whitespaces. I wanted to show the time under the image but you do not allow to choose timestamp field, not sure based on which criteria. I had to add my own timestamp field as a "human readable" string field in Grafana SQL request and then use it in your widget. 
Anyway, thx for you work!

**Comment by Dalvany** [comment]
Hello @ivanshilo , thank you for the update.
I'll probably stick for the moment with the current default settings for the URL, I find more likely to open something else than the image. But open a new issue anyway.
For the text alignment I centered it at first but ran into an issue with overflow, can't make it display the start of the text... I'm not enough good at CSS to know if I misused and/or if I can do anything. At least I can add a setting to allow choosing alignment. Can you open a new issue so I'll remember next time I'll work on it.
As for timestamp, it might in deed be good thing, can you open another issue on that and I'll see what I can do.
