### ISSUE TITLE
Image slideshow for panel

### ISSUE THREAD

**Issue by f0ma** [Dalvany/dalvany-image-panel#35]
Hello!

Do you have a plan to add opportunity to display image series as slideshow for your plugin? I think it's a useful feature.

Currently to make it I use dirty jquery hack:
```
setInterval(function(){
    $('div.container').each(function(){
        $(this).children('img').hide();
        var len = $(this).children('img').length;
        var idx = Math.round(Date.now() / 1000) % len;
        $(this).children('img:eq('+idx+')').show();
    })
}, 1000);
```
It works but it is a really ugly solution.

**Comment by Dalvany** [comment]
Hello, thanks for using the plugin. I'll see what I can do but don't expect it soon, I'd like to work on #22 before and I have started yet.

**Comment by f0ma** [comment]
In any case thank you for your job!

**Comment by Dalvany** [comment]
I'll add the effect selection.

**Comment by Dalvany** [comment]
And another setting to choose transition duration

**Comment by Dalvany** [comment]
@f0ma, I made the changes and updated [pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.4.0), you can choose between `Slide`and `Fade` transitions (can't make the `Zoom` one working though) and set the transition duration. But I'll keep `Slide` and 1000 ms transition as defaults.

**Comment by f0ma** [comment]
@Dalvany, Thank you! Works perfectly. But I was not found this changes in pre-release bundle, only in commit https://github.com/Dalvany/dalvany-image-panel/commit/7fa101dbc340a5c230f2c3f557f0fd782acf53b5

**Comment by Dalvany** [comment]
@f0ma Sorry I might have made a mistake, the v2.4.0 tag doesn't seem to link to the latest commit. I'll redo the pre-release.

**Comment by Dalvany** [comment]
Fix, now the tag and [the pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.4.0) use the correct [commit](https://github.com/Dalvany/dalvany-image-panel/commit/7fa101dbc340a5c230f2c3f557f0fd782acf53b5)

**Comment by Dalvany** [comment]
I will publish the release on grafana.
