### ISSUE TITLE
[Feature Request] Underline Justification and Colour

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [Dalvany/dalvany-image-panel#46]
I'd like an option to set the justification of the underline text. Currently the text is always justified to the left, but I'd like to be able to center it.  
Furthermore, I'd like to be able to change its colour like how you can change threshold colours.

**Comment by PlanetTeamSpeakk** [comment]
It'd also be nice if you could vertically align the underline text. It wouldn't be much of 'underline' anymore, but being able to put the text next to or above the image would be great.

**Comment by Dalvany** [comment]
Can you test this [pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.5.0) ?

**Comment by PlanetTeamSpeakk** [comment]
Perfect 👌
