### ISSUE TITLE
(Similar to Issue #68) - Alert icon displayed when query returns no data

### ISSUE THREAD

**Issue by dazzatronic** [Dalvany/dalvany-image-panel#80]
Hi again, Dalvany.

Over the past week or so, our dynamic image panels have started displaying an alert icon again when the query returns no rows. 

This is very similar to what was happening back in Issue #68 except this time the error message (pop-up) is: "Cannot read properties of undefined (reading 'values')"

![image](https://github.com/Dalvany/dalvany-image-panel/assets/122514028/30d0ca6f-fe63-4f9c-841c-d70e46cbfc3e)

As before, the table view in the panel's edit screen correctly displays a "No data" message. 
When the query is returning valid image addresses the panel seems to work fine.

Sure hope you can help (again). 
Thanks

**Comment by Dalvany** [comment]
Hello @dazzatronic, I'm not sure how to reproduce, can you show a capture of the `Query inspector` (`Data` and `Query` tabs) ?

**Comment by Dalvany** [comment]
Can you also tell me what is your grafana's version ?

**Comment by Dalvany** [comment]
Hello thanks for the update, I think I will be able to reproduce knowing the backend (MySQL) and the query that might raise the error

**Comment by Dalvany** [comment]
@dazzatronic I made some changes, I wasn't able to reproduce exactly the same error but I believe it should fix the error.

Can you test this  [pre-release](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v2.9.0) ? You might need to allow unsigned plugin (using docker you should pass an environment variable `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=dalvany-image-panel`).

You can also install it directly from github using docker using the previous environment variable and the following one `GF_INSTALL_PLUGINS=https://github.com/Dalvany/dalvany-image-panel/releases/download/v2.9.0/dalvany-image-panel-2.9.0.zip;dalvany-image-panel`

**Comment by Dalvany** [comment]
I made a release 3.0.0 which requires at least grafana 10. I close this issue, don't hesitate to re-open if there is still any trouble.
