### ISSUE TITLE
Add option to define fallback image

### ISSUE THREAD

**Issue by PhilippDehner** [Dalvany/dalvany-image-panel#89]
If the image is not available, a default / fallback image should be shown. Create a field in the options to define the fallback image.

**Comment by Dalvany** [comment]
Hello @PhilippDehner 
I made a pre-release [here](https://github.com/Dalvany/dalvany-image-panel/releases/tag/v3.1.0). Can you download and install the plugin using the zip file in a test environment and let me know if it's ok ?

**Comment by PhilippDehner** [comment]
@Dalvany Thank you very much, your definition of "not soon" is really nice!
For me it works.

**Comment by Dalvany** [comment]
> @Dalvany Thank you very much, your definition of "not soon" is really nice! For me it works.

Yeah, I had some spare time I didn't mind spending on the plugin and I found a solution of some sort :')

And thanks for spotting `Alt field` I didn't thought about it, I'll fix it.

I'll try to see if I can fix a couple of bugs before submitting a proper release to grafana.
